image: node:10.15

clone:
  depth: full

# Deploy the master branch to our app.
# Pulls the Heroku API Key and the name of the app from our configured environment variables.
herokuAppDeployment: &herokuAppDeployment
  name: Deploy Heroku App
  script:
    - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master -f

pipelines:
  # Deploy the master branch to our app whenever it is updated
  branches:
    master:
      - step: *herokuAppDeployment
